### ISSUE TITLE
Error when running Fragmentarium-2.0.b compiled on Mac OS

### ISSUE THREAD

**Issue by valera-rozuvan** [3Dickulus/FragM#1]
Hello there! I managed to successfully compile Fragmentarium from latest master ( https://github.com/3Dickulus/FragM/tree/63f3657e18cb9a9692283ae78036ff44f6a5a69b ) on my Mac OS machine. However, when running it, I get an error in the console:

```
Segmentation fault: 11
```

Here is the complete error log which is generated by Mac OS: [https://pastebin.com/H3EF1AJ9](https://pastebin.com/H3EF1AJ9). How to best determine the cause of this issue?

**Comment by 3Dickulus** [comment]
Hi and thanks for testing this :D

I don't have a Mac for testing but a couple of suggestions...

check changes and refresh sources from git
turn off USE_OPEN_EXR
turn off NVIDIAGL4PLUS
and set CMAKE_BUILD_TYPE = Debug

also check the APPLE/MAC stuff in the main toplevel CMakeLists.txt file
compile and run from console/cmdline using a debugger (on linux I use -> gdb 
Fragmentarium)

this should give more useful feedback

the problem you describe sounds like a variable is getting referenced before 
it is initialized, this may happen if it is run from the build folder and 
can't find the shader includes, if you have already installed and older version 
you can move the 2.0 executable into the same folder as, say, 
Fragmentarium-1.0.31, because the sh

**Comment by valera-rozuvan** [comment]
It helped. The program launches OK, and seems to work OK so far.

By the way, to make it compile on my system, I had to change:

```
FIND_LIBRARY(OpenGL_LIBRARY GL )
MARK_AS_ADVANCED (OpenGL_LIBRARY)
...
target_link_libraries ( Fragmentarium-2.0.b ${OpenGL_LIBRARY} ${OpenEXR_LIBRARIES} )
```

to

```
find_package(OpenGL REQUIRED)
include_directories(${OPENGL_INCLUDE_DIR})
link_libraries(${OPENGL_LIBRARIES})
...
target_link_libraries ( Fragmentarium-2.0.b ${OpenGL} ${OpenEXR_LIBRARIES} )
```

in CMakeLists.txt file. I am running CMake version 3.8.2.

**Comment by 3Dickulus** [comment]
This fails on my system as you

**Comment by valera-rozuvan** [comment]
What I did to make it work:

1.) `git pull origin master`
Did this to get latest changes.

2.) Like you said:

```
turn off USE_OPEN_EXR
turn off NVIDIAGL4PLUS
and set CMAKE_BUILD_TYPE = Debug
```

3.) Regenerate build tree with CMake.

4.) Compile (with `make -j 4` command).

5.) Copy generated executable to `src` folder (`build` folder is inside the `src` folder).

6.) Run the executable. All is fine :)

**Comment by valera-rozuvan** [comment]
@3Dickulus What's the version of your CMake?

**Comment by 3Dickulus** [comment]
Good to hear, I will look at doing some testing at startup so that it doesn't segfault and exits gracefully with a warning. Although on linux it runs under those conditions (no includes folder) it just doesn't create and show the GL area, with lots of red(fail) and yellow(warn) lines in the log window.

cmake version 3.5.2

**Comment by 3Dickulus** [comment]
just reviewing an earlier version of the cmakelists.txt file, before moving to v2.0 it looked like...
`IF(UNIX)
FIND_LIBRARY(OpenGL_LIBRARY GL )
ELSEIF(APPLE)
FIND_LIBRARY(OpenGL_LIBRARY OpenGL )
ELSEIF(WIN32)
set(OpenGL_LIBRARY "-lopengl32" )
ENDIF ()
`
I recall it was because the GL lib was not getting found properly (back then) but **find_package ( OpenGL REQUIRED )** seems to do the trick now.

Just need the same for OpenEXR, I will update the git repo :)

**Comment by quiret** [comment]
I don't know where else to post this BUT THANK YOU VERY MUCB YOU AMAZING GUY FOR POSTING HOW TO LINK X11 ON LINUX BECAUSE WTF THE LIBFILE FOR XISelectEvents IS CALLED libXi.a HOW WOULD ANYONE KNOW THIS!!! http://www.fractalforums.com/index.php?topic=20428.msg79365#msg79365

**Comment by 3Dickulus** [comment]
uhm... the compiler uses the "lib" prefix and ".a" or ".so" suffix based on the dev package you have installed so "-lXi" will refer to the library "libXi.a" (static libs) or "libXi.so" (dynamic libs)

consult your compiler docs for setting up the link lib paths and suffix
