### ISSUE TITLE
Whole Window renders black and flickers if interaction with it occurs

### ISSUE THREAD

**Issue by Philipp-M** [3Dickulus/FragM#16]
The current version (commit 242f0d1ac106d4e66fc2e83305fc0e0c483c8169)
produces a black screen right after starting the application. The (whole) window flickers between the content that should be shown and black while interacting with it (e.g. selection of text). Though it stays black when interaction stops.

My setup is as following:

Arch linux
Nvidia GTX 1080 with most recent nvidia driver

I tried to check the commit history since when it occurs and could identify the last flickerfree commit that compiles:
431cb0acccaa5305fce67cebf4b0bc1472e2a35e

maybe this helps to reduce the necessary code review, I'm currently checking the changes, but as there are quite some few since then, I don't know exactly where to start looking for potential "flicker-triggers".

**Comment by Philipp-M** [comment]
Ok I found a potential fix by changing
```cpp
fmt.setSwapBehavior(QSurfaceFormat::SingleBuffer);
```
to 
```cpp
fmt.setSwapBehavior(QSurfaceFormat::DoubleBuffer);
```
in MainWindow.cpp:551

**Comment by 3Dickulus** [comment]
FragM uses previewBuffer backBuffer hiresBuffer, accumulating subframes between 2 active buffers, hiresBuffer is used when rendering large tiled images. Why singlebuffer? because when using unconventional rendering methods swapping buffers automatically may interfere with subframe accumulation and I recall reading in the Qt docs that it would be advantageous to use singlebuffer mode. Since moving to QOpenGL from QGL this does not seem to be a problem any longer, at least on linux systems.

Added your pull request and waiting for some input from Win and OSX users. Hopefully the Qt subsystem will manage this well between different OSs.
