### ISSUE TITLE
edit command script can only load a script once

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#35]
1. launch fragm
2. frag already loaded from last session
3. select command script menu
4. cancel (don't load script)
5. type something
6. execute script
7. close dialog
8. select command script menu
9. PROBLEM no way to load a script any more, it goes straight to editor with previous typing

moreover it's not possible to load an .fqs in the main editor (even after selecting show all files)

**Comment by 3Dickulus** [comment]
when the script edit window is closed it keeps whatever was there, if the script is empty (cleared before closing) it will prompt for a file when you call the edit window again

**Comment by claudeha** [comment]
oh! the content of the script window is not stored unless i hit Execute.  deleting all content, hitting Execute, then closing and reopening gives a file browser prompt again

**Comment by 3Dickulus** [comment]
you're right, it doesn't keep script source until it actually gets used (by selecting execute), there was some logic behind that behavior, thinking back to when I implemented scripting, it was to ensure that it only held a working script

it will also segfault and core dump if it tries to save an image to a non-existant folder under script control. it should behave nicely and simply report the error or ask if the folder should be created?

will keep this open then until some internal testing is written to ensure it doesn't do that, I would like to add source highlighting too, or file watch so you can use your favorite editor instead of the simple/basic editor that FragM provides now.

**Comment by claudeha** [comment]
if it used a regular FragM editor tab, the reload stuff might work automagically? may be a bit awkward to have different language syntax highlight in different tabs? must have implicit `#donotrun` for .fqs I suppose too..

**Comment by 3Dickulus** [comment]
no, I don't think so, it would be using it's own parser and highlight engine, frag tabs would use TextEdit class and script tabs could use ScriptEdit class, these tabs would not be connected to the GL draw area like the frag tabs are but they would have to be connected to the frag that it is supposed to operate on or it would possibly get very confused when the script executes without a frag tab active and current.

**Comment by 3Dickulus** [comment]
keeps script if not executed
calls file dialog on open if no script loaded
calls file dialog from "Load" button replaces current editor contents
