### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [3Dickulus/FragM#41]
https://github.com/3Dickulus/FragM/blob/3180c78fb3241abe8c8e36935628abad4f1c3077/.travis.yml#L119

Please provide the AppImage for download on GitHub Releases, thank you.

**Comment by 3Dickulus** [comment]
I have provided an AppImage built on SuSE Leap 15.0 that works on my machine.
linuxdeployqt-continuous-x86_64.AppImage fails on travis because of it's reliance on gtk2 and qt4,
when it works properly on travis I will provide an Ubuntu based AppImage

**Comment by probonopd** [comment]
`linuxdeployqt` should not need gtk2 nor qt4. It's using its own bundled subset of Qt 5. Please provide logs. Thanks.

**Comment by 3Dickulus** [comment]
linuxdeployqt itself runs fine on travis but the resulting AppImage fails with segfault+core dump

https://github.com/probonopd/linuxdeployqt/issues/338

from one of my first attempts on travis...

WARNING: Plugin "/usr/lib/x86_64-linux-gnu/qt4/plugins/platformthemes/libqgtk2.so" not found, skipping
WARNING: Plugin "/usr/lib/x86_64-linux-gnu/qt4/plugins/styles/libqgtk2style.so" not found, skipping
ERROR: findDependencyInfo: "ldd: /usr/lib/x86_64-linux-gnu/qt4/plugins/platforms/libqxcb.so: No such file or directory\n"
ERROR: getBinaryRPaths: "objdump: '/usr/lib/x86_64-linux-gnu/qt4/plugins/platforms/libqxcb.so': No such file\n"
ERROR: file copy failed from "/usr/lib/x86_64-linux-gnu/qt4/plugins/platforms/libqxcb.so"
ERROR:  to "/home/travis/build/[secure]/FragM/Fragmentarium-Source/build/appdir/usr/bin/..//plugins/platforms/libqxcb.so"
ERROR: Could not find any translations in  "/usr/share/qt4/translations"  (developer build?)

...this was confusing because my app uses Qt5 and after sorting out the problems and getting the right libs by passing the -qmake=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake option there were still many failed attempts and finally when there were no ERRORs it still core dumped when executed on my local machine, so I built an appimage locally and it seems to work, just waiting for some feedback from beta testers now.

This method is not ideal for this app, it has a lot of support files that should be accessible from outside of the image. But it's a good way to demo and test the app to see if one wants to put the effort into compiling their own optimized version.

**Comment by probonopd** [comment]
Which version of linuxdeployqt are you using? Please retry using https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage.

**Comment by 3Dickulus** [comment]
using wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" as recommended in the docs.

Can you test run my app image ?

**Comment by probonopd** [comment]
> Can you test run my app image ?

Sure, where can I download it?

**Comment by 3Dickulus** [comment]
On the releases page of this repo https://github.com/3Dickulus/FragM/releases/latest 
recommend nVidia gfx card using proprietary drivers, not guaranteed to work with opensource drivers, should work with other gfx cards if they support compatibility profile, recently found to work with Mac using core profile.

I do like the idea of appimage but I have to say I favour the idea of compiling from source because the final product is optimized for the machine it runs on.
