### ISSUE TITLE
uniform parser does not respect conditions

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#54]
This doesn't work:

```
#if __VERSION__ >= 400
uniform dvec2 Center; slider[(-100,-100),(0,0),(100,100)] NotLockable
#else
uniform vec2 Center; slider[(-100,-100),(0,0),(100,100)] NotLockable
#endif
```

It sometimes creates two `Center` sliders, only one of which is operational, and the precision is a bit hit and miss (ie, sometimes the slider is float only).

I want this for graceful download of frags to single precision where double precision is not supported...

**Comment by claudeha** [comment]
Can't reproduce the two-slider issue any more.  What works:

0. launch an empty fragm session (if tabs are open, close them all and restart)
1. open target frag with version 400 and if clause as above
2. center slider is double precision
3. change version to 330 and rebuild
4. center slider switches to single precision

What doesn't work

5. change version back to 400 and rebuild
6. center slider remains single precision (**bug**)

What helps sometimes

7. create a new 3D camera frag and build it
8. switch back to 400 with 2d camera and rebuild it
9. sometimes this gets the center slider back to double precision

**Comment by 3Dickulus** [comment]
why? the source is parsed for widgets and widget stuff is removed before compiling, the simple internal parser does not know what `#if #else #endif` is or does so it creates 2 widgets...
and here's why the extra one remains...
after compiling, uniforms that are not used get optimized out, if this happens we remove the erroneous widget, however, in this case one uniform never creates a widget and we can't detect the optimizing out because it doesn't get optimized out, compounding this special case is the fact that they have the same name, if they had different names the unused one would probably get removed/hidden ( try Center3 and Center4 ? )

Given the way the FragM internals work this behavior is actually expected.

So, the solution, aisi, is to write a float frag (pre4) and a double frag (post4) and not try to accommodate other versions with this kind of testing in the frag code or the FragM code. Fragment code is not supposed to universally cover special cases, it is task specific, written to do one job in one way and not expected to take into consideration weird conditions beyond what it is meant to do.

Of course this is my own opinion and may differ from mainstream and standards but on the development side it keeps thing simpler I think.

**Comment by claudeha** [comment]
Oh! Yes I see it can be problematic to write a "proper" parser, because some values are defined by the compiler like `__VERSION__` (etc for available GLSL extensions, ...) and can't easily be accessed outside of shader code.  So I will close this as it is unfixable.

> try Center3 and Center4 ?

```
Could not find Center interface widget
```
and gives me both sliders anyway.

I'll stick to my code above given that it mostly works, and note that it is unsupported, at my own risk, etc.

I do prefer to write/maintain code once and not copy/paste bugs all over the place, let's see how far I can get with this approach :)
