### ISSUE TITLE
Fragmentarium-2.0.b segmentation fault

### ISSUE THREAD

**Issue by Kosti1** [3Dickulus/FragM#6]
qt5ct: using qt5ct plugin
Segmentation fault (core dumped)
Using Manjaro (arch linux based)
I do not know where the core got dumped

**Comment by 3Dickulus** [comment]
I can only offer help for the supported distributions, I have to assume that you are referring to running one of the binary packages from the release page. The binaries for the currently supported linux distributions require OpenEXR and a gfx card that supports GL greater than v3.3 is recommended.

re: Manjaro, quote from their website "Manjaro Linux is a new linux distribution which is based on arch linux."
I have never heard of this dist until now, I do not support (regrettably) opensource gfx card drivers, Fragmentarium is developed on nVidia hardware using the official drivers from nVidia.

Supported distributions are Ubuntu (Debian) and SuSE Leap 42.2, I would suggest that you try the Windows version using Wine because that package contains 4 executable versions in different nV+EXR flavors, try the nonv-noexr one first and move up from there.

A note to all linux users: you should compile it from source on your machine to get an executable that is best for your hardware.

you can find notes for compiling different versions here https://en.wikibooks.org/w/index.php?title=Fractals/fragmentarium&stable=0#Intro
