### ISSUE TITLE
can't load large EXR image

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#89]
**Describe the bug**
EXR loader image dimensions are artificially limited.  Either that or the reported maximum OpenGL texture size is wrong.  Probably maximum texture size depends on texture internal format?

**To Reproduce**
1. try to load a big EXR:
```
Maximum texture size: 16384x16384
Exrloader found EXR image: 6400 x 3600 is too large! max 4096x4096
Not a valid texture: /home/claude/cycle-source.exr
```

**Expected behavior**
EXR images with dimensions up to maximum texture size can be loaded.

**Desktop (please complete the following information):**
 - FragM: master
 - OS: Debian Buster
 - Gfx card: AMD RX 580
 - Driver version: Vendor: X.Org Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 4.19.0-6-amd64, LLVM 7.0.1) GL Driver: 4.5 (Compatibility Profile) Mesa 18.3.6 

**Additional context**
Wanting to colourize large raw iteration data EXRs from KF.  Will experiment with smaller images for the moment.

**Comment by claudeha** [comment]
removing the (arbitrary?) `s/=4` and I can load the 6400x3600 file

**Comment by 3Dickulus** [comment]
6400x3600 = 23040000 ? your driver reports GL_MAX_TEXTURE_SIZE = 16384x16384 I'm not sure if that represents bytes or pixels, in the later case removing the `s /= 4;` is not a problem, some manufacturers report GL_MAX_TEXTURE_SIZE value but do not enforce it allowing out of spec sizes, and newer stuff allows X!=Y textures not only (X==Y)^2
but still need to test WH against GL_MAX_TEXTURE_SIZE limit though.
```
...
Device 0: "GeForce GTX 760"
  Max Texture Dimension Sizes                    1D=(65536) 2D=(65536,65536) 3D=(4096,4096,4096)
  Max Layered Texture Size (dim) x layers        1D=(16384) x 2048, 2D=(16384,16384) x 2048
...
```
errors related to GL_MAX_TEXTURE_SIZE https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glTexImage2D.xml
> 
> GL_INVALID_VALUE is generated if width or height is less than 0 or greater than 2 + GL_MAX_TEXTURE_SIZE.
> GL_INVALID_VALUE may be generated if level is greater than log2(max), where max is the returned value of GL_MAX_TEXTURE_SIZE.
>

**Comment by 3Dickulus** [comment]
is the iteration data file in tiled format? for what you want to do it would be better because the max texture size would be the size of one tile, this would remove any (almost?) size restrictions.

> Wanting to colourize large raw iteration data EXRs from KF.

if this is the only use for this feature then I'm not really interested in adding a bunch of code and having to maintain it, FrgaM is already too cluttered. I am interested in being able to load the RGBZ format EXRs because FragM creates them and can use them in a meaningful way. 

Don't get me wrong, I like the idea but I've had 0 input from 0 people regarding this subject. I also feel it would be much better to write a small efficient plugin for KFR that uses the GPU to colourize iteration data rather than hacking it into FragM.

BTW master is lagging behind Dev branch, only updating master when there are no major errors or bugs reported in Dev, master currently has bugs that may have been fixed in Dev.

I also don't really want to add more code until the bug population has been reduced to little or nothing and any new features have been thoroughly tested.

**Comment by claudeha** [comment]
1. it's not tiled, regular scanline EXR
2. it's the only use I personally have so far. I do plan to add EXR export to some of my other programs too, but that would still be mostly in the realms of "colourizing raw 2d iteration data".
3. yes feedback from community is lacking. but for my own purposes, prototyping colouring algorithms in FragM is much quicker workflow than recompiling code in KF would be, not to mention not having the uniform GUI support, scripting, texture(s) loading, etc etc
4. I noticed the dev branch exists, basing any bug reports and future PRs on it
5. ok, noted.  the code is written and works for me, the PR is published so 3rd parties can try it out if they like, everyone can maintain their own fork with various features plucked from various sources - so I don't feel to precious about having "wasted time" or anything like that :)

**Comment by 3Dickulus** [comment]
When things are learned and useful tools are made it's definitely **not** a waste of time.
